object Deps {


    const val CLASS_PATH_GRADLE = "com.android.tools.build:gradle:7.2.2"
    const val CLASS_PATH_KOTLIN = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.KOTLIN}"
    const val CLASS_PATH_BUGLY = "com.tencent.bugly:symtabfileuploader:2.2.1"
    const val CLASS_PATH_ROBUST = "com.meituan.robust:gradle-plugin:0.4.99"
    const val CLASS_PATH_ROBUST_PATCH = "com.meituan.robust:auto-patch-plugin:0.4.99"
    const val CLASS_PATH_HUAWEI = "com.huawei.agconnect:agcp:1.0.0.300"


    const val APPCOMPAT = "androidx.appcompat:appcompat:1.1.0"
    const val SUPPORT_V4 = "androidx.legacy:legacy-support-v4:1.0.0"
    const val MATERIAL = "com.google.android.material:material:1.0.0"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.1.0"
    const val GRID_LAYOUT = "androidx.gridlayout:gridlayout:1.0.0"
    const val ANNOTATION = "androidx.annotation:annotation:1.1.0"
    const val CARD_VIEW = "androidx.cardview:cardview:1.0.0"
    const val VIEWPAGER2 = "androidx.viewpager2:viewpager2:1.0.0"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:1.1.3"
    const val EXIF = "androidx.exifinterface:exifinterface:1.3.0"
    const val START_UP = "androidx.startup:startup-runtime:1.0.0"

    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.KOTLIN}"
    const val KOTLIN_COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7"
    const val KOTLIN_COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.7"

    const val CORE_KTX = "androidx.core:core-ktx:1.3.0"
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx:1.2.2"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx:1.3.6"
    const val VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.0"
    const val LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:2.5.0"
    const val RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.0"
    const val PROCESS_KTX = "androidx.lifecycle:lifecycle-process:2.5.0"
    const val EXTENSIONS_KTX = "androidx.lifecycle:lifecycle-extensions:2.5.0"

    const val AV_SDK = "com.tencent.liteav:LiteAVSDK_Professional:7.6.9376"
    const val RXJAVA2 = "io.reactivex.rxjava2:rxjava:2.2.0"
    const val RXANDROID2 = "io.reactivex.rxjava2:rxandroid:2.0.2"
    const val OKHTTP_LOG = "com.squareup.okhttp3:logging-interceptor:3.9.0"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:2.6.1"
    const val RETROFIT_ADAPTER_RXJAVA2 = "com.squareup.retrofit2:adapter-rxjava2:2.6.1"
    const val RETROFIT_CONVERTER_GSON = "com.squareup.retrofit2:converter-gson:2.6.1"
    const val OKHTTP_UTIL = "com.zhy:okhttputils:2.6.2"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:3.12.1"
    const val OKIO = "com.squareup.okio:okio:1.15.0"
    const val OKOKHTTP_URL = "com.squareup.okhttp3:okhttp-urlconnection:3.12.1"
    const val STETHO = "com.facebook.stetho:stetho:1.5.1"
    const val STETHO_OKHTTP = "com.facebook.stetho:stetho-okhttp3:1.5.1"
    const val X5WEBVIEW = "com.tencent.tbs.tbssdk:sdk:43903"
    const val GSON = "com.google.code.gson:gson:2.8.0"
    const val MULTI_TYPE_ADAPTER = "me.drakeet.multitype:multitype:3.4.0"
    const val GLIDE = "com.github.bumptech.glide:glide:4.7.1"
    const val GLIDE_OKHTTP = "com.github.bumptech.glide:okhttp3-integration:4.7.1"
    const val NINEOLD = "com.nineoldandroids:library:2.4.0"
    const val VIEWPAGER_INDICATOR = "com.github.JakeWharton:ViewPagerIndicator:2.4.1"
    const val BASE_ADAPTER = "com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.47"
    const val BLANKJ = "com.blankj:utilcode:1.25.5"
    const val SWIPE_MENU = "com.github.anzaizai:EasySwipeMenuLayout:1.1.4"
    const val ROUND_IMAGEVIEW = "com.makeramen:roundedimageview:2.3.0"
    const val COS_XML = "com.tencent.qcloud:cosxml:5.4.20"
    const val LUBAN = "top.zibin:Luban:1.1.3"
    const val QINIU = "com.qiniu:qiniu-android-sdk:7.3.13"
    const val PERMISSION = "com.yanzhenjie:permission:2.0.0-rc12"
    const val ALERT_DIALOG = "com.yanzhenjie.alertdialog:alertdialog:1.0.1"
    const val GLIDE_TRANSFORM = "jp.wasabeef:glide-transformations:3.3.0"
    const val BLOCK_CANARY = "com.github.markzhai:blockcanary-android:1.5.0"
    const val BLOCK_CANARY_NO_OP = "com.github.markzhai:blockcanary-no-op:1.5.0"
    const val PACKER = "com.mcxiaoke.packer-ng:helper:2.0.1"
    const val ZXING = "com.google.zxing:core:3.2.1"
    const val QR_CODE_CORE = "cn.bingoogolapple:bga-qrcodecore:1.1.7@aar"
    const val BGA_ZXING = "cn.bingoogolapple:bga-zxing:1.1.7@aar"
    const val PHOTO_VIEW = "com.github.chrisbanes:PhotoView:2.0.0"
    const val STATUS_BAR = "com.githang:status-bar-compat:0.7"
    const val EVENT_BUS = "org.greenrobot:eventbus:3.1.1"
    const val BUGLY = "com.tencent.bugly:crashreport_upgrade:1.3.5"

    const val HTML_CLEANER = "net.sourceforge.htmlcleaner:htmlcleaner:2.16"
    const val WE_CHAT_SDK = "com.tencent.mm.opensdk:wechat-sdk-android-without-mta:5.5.8"
    const val PICKER_VIEW = "com.contrarywind:Android-PickerView:4.1.8"
    const val BUTTER_KNIFE = "com.jakewharton:butterknife:10.2.1"
    const val BUTTER_KNIFE_COMPILER = "com.jakewharton:butterknife-compiler:10.2.1"
    const val SMART_REFRESH_LAYOUT = "com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1"
    const val SMART_REFRESH_HEADER = "com.scwang.smartrefresh:SmartRefreshHeader:1.0.5.1"
    const val ZYP_CARD_VIEW = "com.zyp.cardview:cardview:1.0.1"
    const val GIF_DRAWABLE = "pl.droidsonroids.gif:android-gif-drawable:1.2.15"
    const val GSY_PLAYER = "com.shuyu:gsyVideoPlayer-java:7.1.3"
    const val GSY_PLAYER_V7A = "com.shuyu:gsyVideoPlayer-armv7a:7.1.3"
    const val BANNER = "com.youth.banner:banner:1.4.9"
    const val FLYCO_TAB_LAYOUT = "com.flyco.tablayout:FlycoTabLayout_Lib:2.1.2@aar"
    const val TENCENT_IM_SDK = "com.tencent.imsdk:imsdk:4.6.1"
    const val BYTE_DANCE_SDK = "com.bytedance.ies.ugc.aweme:opensdk-china-external:0.1.0.0"
    const val BYTE_DANCE_COMMON = "com.bytedance.ies.ugc.aweme:opensdk-common:0.1.0.0"
    const val ROBUST = "com.meituan.robust:robust:0.4.99"
    const val SVGA_PLAYER = "com.github.svga:SVGAPlayer-Android:2.5.3"
    const val GUIDE_VIEW = "com.binioter:guideview:1.0.0"
    const val MMKV = "com.tencent:mmkv-static:1.2.4"
    const val TENCENT_LOCATION_SDK =
        "com.tencent.map.geolocation:TencentLocationSdk-openplatform:7.2.6"
    const val TENCENT_MAP_UTIL = "com.tencent.map:sdk-utilities:1.0.5"
    const val TENCENT_MAP_VECTOR = "com.tencent.map:tencent-map-vector-sdk:4.3.0"
    const val TENCENT_MAP_SDK = "com.tencent.map:sdk-compat-v4:4.2.8"
    const val FAST_JSON = "com.alibaba:fastjson:1.2.56"
    const val ULTRA_VP = "com.alibaba.android:ultraviewpager:1.0.7.8@aar"
    const val IMAGE_CROP = "com.theartofdev.edmodo:android-image-cropper:2.8.0"

    //CameraX相关
    const val CAMERAX_BASIC = "androidx.camera:camera-camera2:1.0.0-beta07"
    const val CAMERAX_VIEW = "androidx.camera:camera-view:1.0.0-alpha14"
    const val CAMERAX_EXT = "androidx.camera:camera-extensions:1.0.0-alpha14"
    const val CAMERAX_LIFECYCLE = "androidx.camera:camera-lifecycle:1.0.0-beta07"

    //指示器
    const val INDICATOR_MAGIC = "com.github.hackware1993:MagicIndicator:1.7.0"  // androidx版本


}